### ISSUE TITLE
[Bug]: RFI data never loaded, always raises warning for zip files

### ISSUE THREAD

**Issue by scottstanie** [isce-framework/s1-reader#127]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

Zipfiles which contain the RFI data don't get loaded. They always raise the warning that the files don't exist.
```
(mapping-311) [staniewi@aurora COMPASS]$ unzip -l tests/data/S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681.zip | grep rfi
        0  02-01-2023 13:39   S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681.SAFE/annotation/rfi/
     7301  02-01-2023 14:28   S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681.SAFE/annotation/rfi/rfi-s1a-iw3-slc-vv-20221016t015045-20221016t015110-045461-056fc0-006.xml
     7301  02-01-2023 14:28   S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681.SAFE/annotation/rfi/rfi-s1a-iw2-slc-vh-20221016t015044-20221016t015109-045461-056fc0-002.xml
     6958  02-01-2023 14:28   S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681.SAFE/annotation/rfi/rfi-s1a-iw1-slc-vv-20221016t015043-20221016t015111-045461-056fc0-004.xml
     7301  02-01-2023 14:28   S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681.SAFE/annotation/rfi/rfi-s1a-iw3-slc-vh-20221016t015045-20221016t015110-045461-056fc0-003.xml
     7301  02-01-2023 14:28   S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681.SAFE/annotation/rfi/rfi-s1a-iw2-slc-vv-20221016t015044-20221016t015109-045461-056fc0-005.xml
     6958  02-01-2023 14:28   S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681.SAFE/annotation/rfi/rfi-s1a-iw1-slc-vh-20221016t015043-20221016t015111-045461-056fc0-001.xml

```

```
(mapping-311) [staniewi@aurora COMPASS]$ s1_info tests/data/S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681.zip
Found 1 Sentinel-1 SLC products.
Bursts in tests/data/S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681.zip:
--------------------------------------------------------------------------------
/u/aurora-r0/staniewi/repos/s1-reader/src/s1reader/s1_reader.py:683: UserWarning: No RFI metadata found at S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681.SAFE/annotation/rfi/rfi-s1a-iw1-slc-vv-20221016t015043-20221016t015111-045461-056fc0-004.xml.
  warnings.warn(f"No RFI metadata found at {rfi_annotation_path}.")
...
```

https://github.com/isce-framework/s1-reader/blob/559f026e5a47f81e010a0bc47d73dc15afc0b1bd/src/s1reader/s1_reader.py#L673-L675

These lines check if a files exists, but it's inside the zip file.

### What did you expect?

- No warning should be printed when there's not an RFI file available, since everything pre-2021 has no RFI and it's not a problem
- we should add a unit test for an example with RFI loading as a minimum smoke test

### Reproducible steps

```bash
`s1_info` on any .zip file will print a `UserWarning`
```

**Comment by seongsujeong** [comment]
Thanks for the report Scott. It looks like the culprit has been introduced from your PR #119  that makes RFI loading optional. So I think you would the best person who can fix that issue. Maybe `try...except` will to the trick.

Let me work on adding a unit test for RFI. That would include not only adding the test code, but also updating the test dataset because the current test data [`S1A_IW_SLC__1SDV_20200511T135117_20200511T135144_032518_03C421_7768.zip`](https://github.com/isce-framework/s1-reader/blob/main/tests/data/S1A_IW_SLC__1SDV_20200511T135117_20200511T135144_032518_03C421_7768.zip) does not have the RFI annotation.
